import { ArrayExercise } from "@utils/interfaces";

export const Exercises: ArrayExercise[] = [
  {
    id: "1",
    type: "Peito",
    img: "https://th.bing.com/th/id/OIP.-I-mbNAVebKR7R1Q1Ee39QHaEo?w=246&h=180&c=7&r=0&o=5&pid=1.7",
    text: "Supino Reto",
    numberOfSeries: 4,
    repetitions: 10,
  },
  {
    id: "2",
    type: "Costas",
    img: "https://th.bing.com/th/id/OIP.nC6zc0nux4xI9RbVRTPnbAHaFj?w=216&h=180&c=7&r=0&o=5&pid=1.7",
    text: "Puxada Alta",
    numberOfSeries: 3,
    repetitions: 12,
  },
  {
    id: "3",
    type: "Ombros",
    img: "https://treinomestre.com.br/wp-content/uploads/2018/09/desenvolvimento-com-halteres-.jpg",
    text: "Desenvolvimento com Halteres",
    numberOfSeries: 4,
    repetitions: 10,
  },
  {
    id: "4",
    type: "Braços",
    img: "https://www.sandrolenzi.com.br/wp-content/uploads/2017/03/rosca-direta-2.jpg",
    text: "Rosca Direta",
    numberOfSeries: 3,
    repetitions: 15,
  },
  {
    id: "5",
    type: "Pernas",
    img: "https://th.bing.com/th/id/R.7457811feab6afa95dd7160ce3adf8b7?rik=zuw74K8SK%2bo9Dg&pid=ImgRaw&r=0",
    text: "Agachamento Livre",
    numberOfSeries: 4,
    repetitions: 12,
  },
  {
    id: "6",
    type: "Panturrilhas",
    img: "https://th.bing.com/th/id/OIP.VXNg4XqVlmn7v344S9OgVAHaE_?rs=1&pid=ImgDetMain",
    text: "Elevação de Panturrilha",
    numberOfSeries: 3,
    repetitions: 20,
  },
  {
    id: "7",
    type: "Abdomen",
    img: "https://th.bing.com/th/id/OIP.OmlyMVLC67UBEm8HlXM0WwAAAA?rs=1&pid=ImgDetMain",
    text: "Abdominal Crunch",
    numberOfSeries: 3,
    repetitions: 15,
  },
  {
    id: "8",
    type: "Triceps",
    img: "https://th.bing.com/th/id/R.c7468c7f88f26f52cf90163c26ec739a?rik=rX5RGjL87ZbY3w&pid=ImgRaw&r=0",
    text: "Tríceps no Pulley",
    numberOfSeries: 3,
    repetitions: 12,
  },
  {
    id: "9",
    type: "Gluteos",
    img: "https://assets.icanet.se/t_epi6imagevault,f_auto/imagevaultfiles/id_136252/cf_259/h-ft.jpg?",
    text: "Elevação de Quadril",
    numberOfSeries: 4,
    repetitions: 15,
  },
  {
    id: "10",
    type: "Antebracos",
    img: "https://www.hipertrofia.org/blog/wp-content/uploads/2018/09/rosca-inversa.jpg",
    text: "Rosca Inversa",
    numberOfSeries: 3,
    repetitions: 12,
  },
];
