import { ArrayExercise } from "@utils/interfaces";

export const Exercises: ArrayExercise[] = [
  {
    id: "1",
    type: "Peito",
    img: "https://www.mundoboaforma.com.br/wp-content/uploads/2020/12/supino-inclinado-com-barra.gif",
    text: "Supino inclinado com barra",
    numberOfSeries: 4,
    repetitions: 10,
  },
  {
    id: "2",
    type: "Costas",
    img: "https://th.bing.com/th/id/OIP.nC6zc0nux4xI9RbVRTPnbAHaFj?w=216&h=180&c=7&r=0&o=5&pid=1.7",
    text: "Puxada Alta",
    numberOfSeries: 3,
    repetitions: 12,
  },
  {
    id: "3",
    type: "Ombros",
    img: "https://treinomestre.com.br/wp-content/uploads/2018/09/desenvolvimento-com-halteres-.jpg",
    text: "Desenvolvimento com Halteres",
    numberOfSeries: 4,
    repetitions: 10,
  },
  {
    id: "4",
    type: "Braços",
    img: "https://www.sandrolenzi.com.br/wp-content/uploads/2017/03/rosca-direta-2.jpg",
    text: "Rosca Direta",
    numberOfSeries: 3,
    repetitions: 15,
  },
  {
    id: "5",
    type: "Pernas",
    img: "https://th.bing.com/th/id/R.7457811feab6afa95dd7160ce3adf8b7?rik=zuw74K8SK%2bo9Dg&pid=ImgRaw&r=0",
    text: "Agachamento Livre",
    numberOfSeries: 4,
    repetitions: 12,
  },
  {
    id: "6",
    type: "Panturrilhas",
    img: "https://th.bing.com/th/id/OIP.VXNg4XqVlmn7v344S9OgVAHaE_?rs=1&pid=ImgDetMain",
    text: "Elevação de Panturrilha",
    numberOfSeries: 3,
    repetitions: 20,
  },
  {
    id: "7",
    type: "Abdomen",
    img: "https://th.bing.com/th/id/OIP.OmlyMVLC67UBEm8HlXM0WwAAAA?rs=1&pid=ImgDetMain",
    text: "Abdominal Crunch",
    numberOfSeries: 3,
    repetitions: 15,
  },
  {
    id: "8",
    type: "Triceps",
    img: "https://th.bing.com/th/id/R.c7468c7f88f26f52cf90163c26ec739a?rik=rX5RGjL87ZbY3w&pid=ImgRaw&r=0",
    text: "Tríceps no Pulley",
    numberOfSeries: 3,
    repetitions: 12,
  },
  {
    id: "9",
    type: "Gluteos",
    img: "https://assets.icanet.se/t_epi6imagevault,f_auto/imagevaultfiles/id_136252/cf_259/h-ft.jpg?",
    text: "Elevação de Quadril",
    numberOfSeries: 4,
    repetitions: 15,
  },
  {
    id: "10",
    type: "Antebracos",
    img: "https://www.hipertrofia.org/blog/wp-content/uploads/2018/09/rosca-inversa.jpg",
    text: "Rosca Inversa",
    numberOfSeries: 3,
    repetitions: 12,
  },
  {
    id: "11",
    type: "Gluteos",
    img: "https://www.belezamasculina.com.br/y/5749/subida-575.webp",
    text: "Step-up",
    numberOfSeries: 3,
    repetitions: 12,
  },
  {
    id: "12",
    type: "Gluteos",
    img: "https://www.belezamasculina.com.br/y/5749/cintura-500.webp",
    text: "Elevação pélvica",
    numberOfSeries: 3,
    repetitions: 12,
  },
  {
    id: "13",
    type: "Antebracos",
    img: "https://www.hipertrofia.org/blog/wp-content/uploads/2017/05/suspensao-barra.jpg",
    text: "Suspensão na barra",
    numberOfSeries: 3,
    repetitions: 12,
  },
  {
    id: "14",
    type: "Triceps",
    img: "https://th.bing.com/th/id/R.d1d32c1eb42adb7789689a07aa55da84?rik=HZB3TJfQZTDjmw&pid=ImgRaw&r=0",
    text: "Tríceps banco",
    numberOfSeries: 3,
    repetitions: 12,
  },
  {
    id: "15",
    type: "Panturrilhas",
    img: "https://www.hipertrofia.org/blog/wp-content/uploads/2018/09/rosca-inversa.jpg",
    text: "Rosca Inversa",
    numberOfSeries: 3,
    repetitions: 12,
  },
  {
    id: "16",
    type: "Panturrilhas",
    img: "https://guiadocorpo.com/wp-content/uploads/2019/09/Treino-de-panturrilha-03.jpg",
    text: "Panturrilha no step",
    numberOfSeries: 3,
    repetitions: 12,
  },
  {
    id: "17",
    type: "Triceps",
    img: "https://th.bing.com/th/id/OIP.yUs0HVz4NQxqrz1EtHKD4gHaFj?rs=1&pid=ImgDetMain",
    text: "Rosca Inversa",
    numberOfSeries: 3,
    repetitions: 12,
  },
  {
    id: "18",
    type: "Braços",
    img: "https://cdn.shopify.com/s/files/1/1637/8923/files/65_600x600.png?v=1697158673",
    text: "Flexão de braços diamante",
    numberOfSeries: 3,
    repetitions: 12,
  },
  {
    id: "19",
    type: "Braços",
    img: "https://th.bing.com/th/id/OIP.1PV6j_JNFW1k3XSqaIDszAHaEU?rs=1&pid=ImgDetMain",
    text: "Rosca bíceps martelo com halteres",
    numberOfSeries: 3,
    repetitions: 12,
  },
  {
    id: "20",
    type: "Ombros",
    img: "https://www.hipertrofia.org/blog/wp-content/uploads/2018/11/desenvolvimento-arnold1-600x327.jpg",
    text: "Desenvolvimento Arnold para ombros",
    numberOfSeries: 3,
    repetitions: 12,
  },
  {
    id: "21",
    type: "Peito",
    img: "https://www.mundoboaforma.com.br/wp-content/uploads/2020/12/supino-reto.gif",
    text: "Supino reto com barra",
    numberOfSeries: 3,
    repetitions: 12,
  },
  {
    id: "22",
    type: "Peito",
    img: "https://www.mundoboaforma.com.br/wp-content/uploads/2020/12/supino-reto-com-halteres.gif",
    text: "Supino reto com halteres",
    numberOfSeries: 3,
    repetitions: 12,
  },
  {
    id: "23",
    type: "Peito",
    img: "https://www.mundoboaforma.com.br/wp-content/uploads/2020/12/flexao-de-bracos.gif",
    text: "Flexão de braços básica",
    numberOfSeries: 3,
    repetitions: 12,
  },
  {
    id: "24",
    type: "Peito",
    img: "https://www.mundoboaforma.com.br/wp-content/uploads/2020/12/flexao-de-bracos-inclinada.gif",
    text: "Flexão de braços inclinada",
    numberOfSeries: 3,
    repetitions: 12,
  },
];
